---
- name: Create directory GWire
  ansible.builtin.file:
    path: /opt/gwire/
    state: directory
    mode: '0755'

- name: Download Bin GWire
  get_url:
    url: https://raw.githubusercontent.com/nilsonvieira/gwireguard/main/gwire
    dest: /opt/gwire/gwire
    mode: '0755'

- name: Create a symbolic link for binary GWire
  ansible.builtin.file:
    src: /opt/gwire/gwire
    dest: /usr/local/bin/gwire
    state: link
